from typing import Literal

CountryLiteral = Literal[
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "France",
    "Germany",
    "Spain",
    "Italy",
    "Romania",
    "Japan",
    "China",
    "India",
    "Brazil",
    "Canada",
    "Australia",
    "Netherlands",
    "Switzerland",
    "Sweden",
    "Norway",
    "Denmark",
    "Korea",
    "Turkey",
    "Poland",
    "Czech Republic",
    "Greece",
    "Portugal",
    "Belgium",
    "Mexico",
    "Singapore",
    "Thailand",
    "Vietnam",
    "Austria",
    "Israel",
    "Finland",
    "Costa Rica",
    "Bulgaria",
    "Saudi Arabia",
    "Peru",
    "Germany",
    "Croatia",
    "Ireland",
    "Czech Republic",
    "New Zealand",
    "Bosnia",
    "Bangladesh",
    "Georgia",
    "Algeria",
    "Sri Lanka",
    "Kuwait",
    "Bahrain",
    "Lithuania",
    "Slovakia",
    "Luxembourg",
    "Malaysia",
    "Moldova",
    "Nigeria",
    "Pakistan",
    "Slovenia",
    "Togdheer",
]
